import HexagonIcon from "@mui/icons-material/Hexagon";
import PentagonIcon from "@mui/icons-material/Pentagon";
import SquareIcon from "@mui/icons-material/Square";
import Heptagon from "assets/icons/Heptagon";
import Octagon from "assets/icons/Octagon";
import Triangle from "assets/icons/Triangle";
export enum ShapeType {
  "accentBorderCallout1" = "accentBorderCallout1",
  "accentBorderCallout2" = "accentBorderCallout2",
  "accentBorderCallout3" = "accentBorderCallout3",
  "accentCallout1" = "accentCallout1",
  "accentCallout2" = "accentCallout2",
  "accentCallout3" = "accentCallout3",
  "actionButtonBackPrevious" = "actionButtonBackPrevious",
  "actionButtonBeginning" = "actionButtonBeginning",
  "actionButtonBlank" = "actionButtonBlank",
  "actionButtonDocument" = "actionButtonDocument",
  "actionButtonEnd" = "actionButtonEnd",
  "actionButtonForwardNext" = "actionButtonForwardNext",
  "actionButtonHelp" = "actionButtonHelp",
  "actionButtonHome" = "actionButtonHome",
  "actionButtonInformation" = "actionButtonInformation",
  "actionButtonMovie" = "actionButtonMovie",
  "actionButtonReturn" = "actionButtonReturn",
  "actionButtonSound" = "actionButtonSound",
  "arc" = "arc",
  "bentArrow" = "bentArrow",
  "bentUpArrow" = "bentUpArrow",
  "bevel" = "bevel",
  "blockArc" = "blockArc",
  "borderCallout1" = "borderCallout1",
  "borderCallout2" = "borderCallout2",
  "borderCallout3" = "borderCallout3",
  "bracePair" = "bracePair",
  "bracketPair" = "bracketPair",
  "callout1" = "callout1",
  "callout2" = "callout2",
  "callout3" = "callout3",
  "can" = "can",
  "chartPlus" = "chartPlus",
  "chartStar" = "chartStar",
  "chartX" = "chartX",
  "chevron" = "chevron",
  "chord" = "chord",
  "circularArrow" = "circularArrow",
  "cloud" = "cloud",
  "cloudCallout" = "cloudCallout",
  "corner" = "corner",
  "cornerTabs" = "cornerTabs",
  "cube" = "cube",
  "curvedDownArrow" = "curvedDownArrow",
  "curvedLeftArrow" = "curvedLeftArrow",
  "curvedRightArrow" = "curvedRightArrow",
  "curvedUpArrow" = "curvedUpArrow",
  "decagon" = "decagon",
  "diagStripe" = "diagStripe",
  "diamond" = "diamond",
  "dodecagon" = "dodecagon",
  "donut" = "donut",
  "doubleWave" = "doubleWave",
  "downArrow" = "downArrow",
  "downArrowCallout" = "downArrowCallout",
  "ellipse" = "ellipse",
  "ellipseRibbon" = "ellipseRibbon",
  "ellipseRibbon2" = "ellipseRibbon2",
  "flowChartAlternateProcess" = "flowChartAlternateProcess",
  "flowChartCollate" = "flowChartCollate",
  "flowChartConnector" = "flowChartConnector",
  "flowChartDecision" = "flowChartDecision",
  "flowChartDelay" = "flowChartDelay",
  "flowChartDisplay" = "flowChartDisplay",
  "flowChartDocument" = "flowChartDocument",
  "flowChartExtract" = "flowChartExtract",
  "flowChartInputOutput" = "flowChartInputOutput",
  "flowChartInternalStorage" = "flowChartInternalStorage",
  "flowChartMagneticDisk" = "flowChartMagneticDisk",
  "flowChartMagneticDrum" = "flowChartMagneticDrum",
  "flowChartMagneticTape" = "flowChartMagneticTape",
  "flowChartManualInput" = "flowChartManualInput",
  "flowChartManualOperation" = "flowChartManualOperation",
  "flowChartMerge" = "flowChartMerge",
  "flowChartMultidocument" = "flowChartMultidocument",
  "flowChartOfflineStorage" = "flowChartOfflineStorage",
  "flowChartOffpageConnector" = "flowChartOffpageConnector",
  "flowChartOnlineStorage" = "flowChartOnlineStorage",
  "flowChartOr" = "flowChartOr",
  "flowChartPredefinedProcess" = "flowChartPredefinedProcess",
  "flowChartPreparation" = "flowChartPreparation",
  "flowChartProcess" = "flowChartProcess",
  "flowChartPunchedCard" = "flowChartPunchedCard",
  "flowChartPunchedTape" = "flowChartPunchedTape",
  "flowChartSort" = "flowChartSort",
  "flowChartSummingJunction" = "flowChartSummingJunction",
  "flowChartTerminator" = "flowChartTerminator",
  "folderCorner" = "folderCorner",
  "frame" = "frame",
  "funnel" = "funnel",
  "gear6" = "gear6",
  "gear9" = "gear9",
  "halfFrame" = "halfFrame",
  "heart" = "heart",
  "heptagon" = "heptagon",
  "hexagon" = "hexagon",
  "homePlate" = "homePlate",
  "horizontalScroll" = "horizontalScroll",
  "irregularSeal1" = "irregularSeal1",
  "irregularSeal2" = "irregularSeal2",
  "leftArrow" = "leftArrow",
  "leftArrowCallout" = "leftArrowCallout",
  "leftBrace" = "leftBrace",
  "leftBracket" = "leftBracket",
  "leftCircularArrow" = "leftCircularArrow",
  "leftRightArrow" = "leftRightArrow",
  "leftRightArrowCallout" = "leftRightArrowCallout",
  "leftRightCircularArrow" = "leftRightCircularArrow",
  "leftRightRibbon" = "leftRightRibbon",
  "leftRightUpArrow" = "leftRightUpArrow",
  "leftUpArrow" = "leftUpArrow",
  "lightningBolt" = "lightningBolt",
  "line" = "line",
  "lineInv" = "lineInv",
  "mathDivide" = "mathDivide",
  "mathEqual" = "mathEqual",
  "mathMinus" = "mathMinus",
  "mathMultiply" = "mathMultiply",
  "mathNotEqual" = "mathNotEqual",
  "mathPlus" = "mathPlus",
  "moon" = "moon",
  "nonIsoscelesTrapezoid" = "nonIsoscelesTrapezoid",
  "noSmoking" = "noSmoking",
  "notchedRightArrow" = "notchedRightArrow",
  "octagon" = "octagon",
  "parallelogram" = "parallelogram",
  "pentagon" = "pentagon",
  "pie" = "pie",
  "pieWedge" = "pieWedge",
  "plaque" = "plaque",
  "plaqueTabs" = "plaqueTabs",
  "plus" = "plus",
  "quadArrow" = "quadArrow",
  "quadArrowCallout" = "quadArrowCallout",
  "rect" = "rect",
  "ribbon" = "ribbon",
  "ribbon2" = "ribbon2",
  "rightArrow" = "rightArrow",
  "rightArrowCallout" = "rightArrowCallout",
  "rightBrace" = "rightBrace",
  "rightBracket" = "rightBracket",
  "round1Rect" = "round1Rect",
  "round2DiagRect" = "round2DiagRect",
  "round2SameRect" = "round2SameRect",
  "roundRect" = "roundRect",
  "rtTriangle" = "rtTriangle",
  "smileyFace" = "smileyFace",
  "snip1Rect" = "snip1Rect",
  "snip2DiagRect" = "snip2DiagRect",
  "snip2SameRect" = "snip2SameRect",
  "snipRoundRect" = "snipRoundRect",
  "squareTabs" = "squareTabs",
  "star10" = "star10",
  "star12" = "star12",
  "star16" = "star16",
  "star24" = "star24",
  "star32" = "star32",
  "star4" = "star4",
  "star5" = "star5",
  "star6" = "star6",
  "star7" = "star7",
  "star8" = "star8",
  "stripedRightArrow" = "stripedRightArrow",
  "sun" = "sun",
  "swooshArrow" = "swooshArrow",
  "teardrop" = "teardrop",
  "trapezoid" = "trapezoid",
  "triangle" = "triangle",
  "upArrow" = "upArrow",
  "upArrowCallout" = "upArrowCallout",
  "upDownArrow" = "upDownArrow",
  "upDownArrowCallout" = "upDownArrowCallout",
  "uturnArrow" = "uturnArrow",
  "verticalScroll" = "verticalScroll",
  "wave" = "wave",
  "wedgeEllipseCallout" = "wedgeEllipseCallout",
  "wedgeRectCallout" = "wedgeRectCallout",
  "wedgeRoundRectCallout" = "wedgeRoundRectCallout",
}
export const shapes = [
  {
    type: "shape",
    id: "triangle",
    icon: <Triangle />,
    sides: 3,
    radius: 50,
    shape_name: ShapeType.triangle,
  },
  {
    type: "shape",
    shape_name: ShapeType.rect,
    id: "square",
    icon: <SquareIcon />,
    sides: 4,
    radius: 50,
  },
  {
    type: "shape",
    id: "pentagon",
    icon: <PentagonIcon />,
    sides: 5,
    radius: 50,
    shape_name: ShapeType.pentagon,
  },
  {
    type: "shape",
    id: "hexagon",
    icon: <HexagonIcon />,
    sides: 6,
    radius: 50,
    shape_name: ShapeType.hexagon,
  },
  {
    type: "shape",
    id: "heptagon",
    icon: <Heptagon />,
    sides: 7,
    radius: 50,
    shape_name: ShapeType.heptagon,
  },
  {
    type: "shape",
    id: "octagon",
    icon: <Octagon />,
    sides: 8,
    radius: 50,
    shape_name: ShapeType.octagon,
  },
];
